name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"   # jalan tiap 12 jam
  workflow_dispatch:          # bisa dijalankan manual
  push:
    branches: ["main"]        # atau ganti sesuai default branch-mu

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: dexsless
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
